# This YAML file contains snapshotter & csi driver API objects,
# which are necessary to run external csi snapshotter for opensds.

kind: Service
apiVersion: v1
metadata:
  name: csi-snapshotter-opensdsplugin-file
  labels:
    app: csi-snapshotter-opensdsplugin-file
spec:
  selector:
    app: csi-snapshotter-opensdsplugin-file
  ports:
    - name: dummy
      port: 12345

---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: csi-snapshotter-opensdsplugin-file
spec:
  serviceName: "csi-snapshotter-opensdsplugin-file"
  replicas: 1
  selector:
    matchLabels:
      app: csi-snapshotter-opensdsplugin-file
  template:
    metadata:
      labels:
        app: csi-snapshotter-opensdsplugin-file
    spec:
      serviceAccount: csi-snapshotter-file
      containers:
        - name: csi-snapshotter
          image: quay.io/k8scsi/csi-snapshotter:v1.2.2
          args:
            - "--snapshotter=csi-opensdsplugin-file"
            - "--csi-address=$(ADDRESS)"
            - "--connection-timeout=15s"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
        - name: opensds
          image: sodafoundation/csiplugin-file:latest
          args :
            - "--csiEndpoint=$(CSI_ENDPOINT)"
            - "--opensdsEndpoint=$(OPENSDS_ENDPOINT)"
            - "--opensdsAuthStrategy=$(OPENSDS_AUTH_STRATEGY)"
            - "--v=8"
          env:
            - name: CSI_ENDPOINT
              value: unix://csi/csi.sock
            - name: OPENSDS_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: csi-configmap-opensdsplugin-file
                  key: opensdsendpoint
            - name: ENABLE_ENCRYPTED
              valueFrom:
                configMapKeyRef:
                  name: csi-configmap-opensdsplugin-file
                  key: enableEncrypted
            - name: PASSWORD_ENCRYPTER
              valueFrom:
                configMapKeyRef:
                  name: csi-configmap-opensdsplugin-file
                  key: passwordencrypter
            - name: OPENSDS_AUTH_STRATEGY
              valueFrom:
                configMapKeyRef:
                  name: csi-configmap-opensdsplugin-file
                  key: opensdsauthstrategy
            - name: OS_AUTH_URL
              valueFrom:
                configMapKeyRef:
                  name: csi-configmap-opensdsplugin-file
                  key: osauthurl
            - name: OS_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: csi-configmap-opensdsplugin-file
                  key: osusername
            - name: OS_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: csi-configmap-opensdsplugin-file
                  key: ospassword
            - name: PASSWORD_ENCRYPTER
              valueFrom:
                configMapKeyRef:
                  name: csi-configmap-opensdsplugin-file
                  key: passwordencrypter
            - name: ENABLE_ENCRYPTED
              valueFrom:
                configMapKeyRef:
                  name: csi-configmap-opensdsplugin-file
                  key: enableEncrypted
            - name: OS_TENANT_NAME
              valueFrom:
                configMapKeyRef:
                  name: csi-configmap-opensdsplugin-file
                  key: ostenantname
            - name: OS_PROJECT_NAME
              valueFrom:
                configMapKeyRef:
                  name: csi-configmap-opensdsplugin-file
                  key: osprojectname
            - name: OS_USER_DOMAIN_ID
              valueFrom:
                configMapKeyRef:
                  name: csi-configmap-opensdsplugin-file
                  key: osuserdomainid
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
            - name: certificate-path
              mountPath: /opt/opensds-security
      volumes:
        - name: socket-dir
          emptyDir:
        - name: certificate-path
          hostPath:
            path: /opt/opensds-security
            type: DirectoryOrCreate
