kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
    spec:
      containers:
        - name: etcd-store
          image: {{ .Values.image.etcd-store }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          volumeMounts:
            - name: etcd-cert-dir
              mountPath: /etc/ssl/certs
        - name: service-broker
          image: {{ .Values.image.service-broker }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          args:
            - --port
            - "8080"
          env:
            - name: OPENSDS_ENDPOINT
              value: {{ .Values.opensdsEndpoint }}
            - name: OPENSDS_AUTH_STRATEGY
              value: {{ .Values.opensdsAuthStrategy }}
            - name: OS_AUTH_URL
              value: {{ .Values.osAuthURL }}
            - name: OS_USERNAME
              value: {{ .Values.osUsername }}
            - name: OS_PASSWORD
              value: {{ .Values.osPassword }}
            - name: OS_TENANT_NAME
              value: {{ .Values.osTenantName }}
            - name: OS_PROJECT_NAME
              value: {{ .Values.osProjectName }}
            - name: OS_USER_DOMAIN_ID
              value: {{ .Values.osUserDomainID }}
          ports:
            - containerPort: 8080
          readinessProbe:
            tcpSocket:
              port: 8080
            failureThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            tcpSocket:
              port: 8080
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 2
      volumes:
        - name: etcd-cert-dir
          hostPath:
            path: /usr/share/ca-certificates/
            type: Directory
