# This YAML file contains driver-registrar & csi driver nodeplugin API objects,
# which are necessary to run csi nodeplugin for opensds.

kind: DaemonSet
apiVersion: apps/v1beta2
metadata:
  name: csi-nodeplugin-opensdsplugin
spec:
  selector:
    matchLabels:
      app: csi-nodeplugin-opensdsplugin
  template:
    metadata:
      labels:
        app: csi-nodeplugin-opensdsplugin
    spec:
      serviceAccount: csi-nodeplugin
      hostNetwork: true
      containers:
        - name: driver-registrar
          image: quay.io/k8scsi/driver-registrar:v0.2.0
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
          env:
            - name: ADDRESS
              value: /var/lib/kubelet/plugins/csi-opensdsplugin/csi.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/kubelet/plugins/csi-opensdsplugin
        - name: opensds
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true
          image: opensdsio/csiplugin:latest
          args :
            - "--csiEndpoint=$(CSI_ENDPOINT)"
            - "--opensdsEndpoint=$(OPENSDS_ENDPOINT)"
          env:
            - name: CSI_ENDPOINT
              value: unix://var/lib/kubelet/plugins/csi-opensdsplugin/csi.sock
            - name: OPENSDS_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: csi-configmap-opensdsplugin
                  key: opensdsendpoint
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/kubelet/plugins/csi-opensdsplugin
            - name: pods-mount-dir
              mountPath: /var/lib/kubelet/pods
              mountPropagation: "Bidirectional"
            - name: pods-probe-dir
              mountPath: /dev
              mountPropagation: "Bidirectional"
            - name: iscsi-dir
              mountPath: /etc/iscsi/
            - name: ceph-dir
              mountPath: /etc/ceph/
      volumes:
        - name: socket-dir
          hostPath:
            path: /var/lib/kubelet/plugins/csi-opensdsplugin
            type: DirectoryOrCreate		
        - name: pods-mount-dir
          hostPath:
            path: /var/lib/kubelet/pods
            type: Directory
        - name: pods-probe-dir
          hostPath:
            path: /dev
            type: Directory
        - name: iscsi-dir
          hostPath:
            path: /etc/iscsi/
            type: Directory
        - name: ceph-dir
          hostPath:
            path: /etc/ceph/
            type: Directory
